### PR TITLE
Fix issue with messages becoming stuck unack'd

### PR DESCRIPTION
**Pull request by wwitzel3**

### CODE REVIEW

**Comment by chrismeyersfsu** [comment]
I would think that creating and destroying the consumer obj in each receive _many call would be as problematic as putting it in a context manager.

**Comment by wwitzel3** [comment]
Works like a charm. And by creating it with the new list of channels each time, you don't have to maintain a list of what is already been bound to.

**Comment by wwitzel3** [comment]
Also I tried going back to the context manager and it falls on its face just like before.

**Comment by wwitzel3** [comment]
Though I did discover we can create it once and just overwrite the queues attribute on the instance and then call consume() and everything sorts itself out.

**Pull request merged**
